language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - PLUGIN_NAME=Search
    - DB=mysql

  matrix:
    - DB=mysql CAKE_VERSION=2.4

matrix:
  include:
    - php: 5.3
      env:
        - CAKE_VERSION=2.4
        - COVERALLS=1
    - php: 5.4
      env:
        - CAKE_VERSION=2.4
        - COVERALLS=1
    - php: 5.5
      env:
        - CAKE_VERSION=2.4
        - COVERALLS=1

before_script:
  - git clone https://github.com/burzum/travis.git --depth 1 ../travis
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
